name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test-headless
    - name: Deploy gh-pages
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        angular_dist_build_folder: dist/ui-spring-webflux
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
